---
'ubuntu-server-1404-x64':
  description: ""
  facts:
    architecture: amd64
    kernel: Linux
    operatingsystem: Ubuntu
    lsbdistid: Ubuntu
    facterversion: "2.4.1"
    kernelmajversion: "3.13"
    kernelrelease: "3.13.0-24-generic"
    kernelversion: "3.13.0"
    lsbdistcodename: trusty
    lsbdistdescription: "Ubuntu 14.04 LTS"
    lsbdistrelease: "14.04"
    lsbmajdistrelease: "14.04"
    operatingsystemrelease: "14.04"
    osfamily: Debian
    rubyversion: "1.9.3"
  provider_specifics:
    vagrant_virtualbox:
      box: 'puppetlabs/ubuntu-14.04-64-nocm'
      box_url: 'https://vagrantcloud.com/puppetlabs/boxes/ubuntu-14.04-64-nocm/versions/1.0.0/providers/virtualbox.box'
    vagrant_vmware_fusion:
      box: 'puppetlabs/ubuntu-14.04-64-nocm'
      box_url: 'https://vagrantcloud.com/puppetlabs/boxes/ubuntu-14.04-64-nocm/versions/1.0.0/providers/vmware_fusion.box'
    vsphere:
      template: 'ubuntu-1404-x86_64'
'centos-70-x64':
  description: ""
  facts:
    kernelrelease: "3.10.0-123.el7.x86_64"
    operatingsystem: CentOS
    kernelmajversion: "3.10"
    architecture: x86_64
    facterversion: "2.4.1"
    kernelversion: "3.10.0"
    operatingsystemrelease: "7.0.1406"
    osfamily: RedHat
    lsbmajdistrelease: "7"
    lsbdistcodename: Core
    lsbdistdescription: "CentOS Linux release 7.0.1406 (Core)"
    lsbdistid: CentOS
    lsbdistrelease: "7.0.1406"
    kernel: Linux
    rubyversion: "2.0.0"
  provider_specifics:
    vagrant_virtualbox:
      box: 'puppetlabs/centos-7.0-64-nocm'
      box_url: 'https://atlas.hashicorp.com/puppetlabs/boxes/centos-7.0-64-nocm/versions/1.0.0/providers/virtualbox.box'
    vagrant_vmware_fusion:
      box: 'puppetlabs/centos-7.0-64-nocm'
      box_url: 'https://atlas.hashicorp.com/puppetlabs/boxes/centos-7.0-64-nocm/versions/1.0.0/providers/vmware_fusion.box'
    vsphere:
      template: 'centos-7-x86_64'
'centos-65-x64':
  description: ""
  facts:
    kernelrelease: "2.6.32-431.el6.x86_64"
    operatingsystem: CentOS
    kernelmajversion: "2.6"
    architecture: x86_64
    facterversion: "2.4.1"
    kernelversion: "2.6.32"
    operatingsystemrelease: "6.5"
    osfamily: RedHat
    lsbmajdistrelease: "6"
    lsbdistcodename: Final
    lsbdistdescription: "CentOS release 6.5 (Final)"
    lsbdistid: CentOS
    lsbdistrelease: "6.5"
    kernel: Linux
    rubyversion: "1.8.7"
  provider_specifics:
    vagrant_virtualbox:
      box: 'puppetlabs/centos-6.5-64-nocm'
      box_url: 'https://atlas.hashicorp.com/puppetlabs/boxes/centos-6.5-64-nocm/versions/1.0.0/providers/virtualbox.box'
    vagrant_vmware_fusion:
      box: 'puppetlabs/centos-6.5-64-nocm'
      box_url: 'https://atlas.hashicorp.com/puppetlabs/boxes/centos-6.5-64-nocm/versions/1.0.0/providers/vmware_fusion.box'
    vsphere:
      template: 'centos-6-x86_64'
